# Generated by Django 4.2.7 on 2023-12-07 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='end_date',
            field=models.DateField(default=management.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.unit'),
        ),
    ]
